/* global React */
const { useState, useEffect } = React;

// Stage 6 — Report
// Drafts Discussion + Conclusion off the Evaluation findings, then offers
// markdown / latex (arXiv) / pdf export buttons + save + open project.

const palette = window.__probePalette;
const kbdStyle = window.__probeKbd;
const ghostBtnStyle = window.__probeGhostBtn;

function defaultDiscussion(rqs) {
  return `Three implications follow from the integrated findings.

First, the dominant framing of meeting-fatigue as load-driven holds, but agenda presence emerges as a more tractable lever than attendee count. Practitioners should default to agenda-required calendars before pursuing meeting-shrinking interventions.

Second, the within-subjects ritual evidence is encouraging but fragile. The effect appears only when the ritual is the only break in the sequence, suggesting that *replacing* an unstructured break may not be additive. This is a clean follow-up study.

Third, the somatic-first texture finding is the strongest qualitative signal in the dataset, and the most underdeveloped thread in the existing literature. A body-mapping replication with a larger sample is warranted.

Threats to validity (simulated): novelty effect in the first 1-2 weeks of probe usage; self-report ceiling on focus measures; sampling skewed toward participants willing to install a desktop helper.

Ethical considerations: no participant lost data, no manager saw individual records, all telemetry was opt-in. The compensation structure ($80 + $20/week) appeared adequate; one synthetic participant flagged it as low for a 4-week commitment, which we should note for any real deployment.`;
}

function defaultConclusion(rqs) {
  return `We integrated three lenses — calendar-structural, intervention, and lived-experience — into a single 12-week study answering the main question of how remote workers maintain focus across video-call days.

The contribution is threefold: (1) a calendar-structural account of within-day focus drop-off that emphasizes agenda-presence over attendee count; (2) preliminary evidence that a single 90-second ritual produces a focus bump under specific conditions; (3) a somatic-first vocabulary for video-call fatigue derived from body-mapping with ${rqs.length} sub-question framings held in view.

Future work should replicate the somatic-first finding outside our sample, run a larger ritual trial, and design calendar-tooling experiments around agenda-presence as the primary lever.`;
}

// ─── Compose a full markdown report from all stages ───
function composeMarkdown({ mainRq, selectedBranches, chosenDesign, plan, evaluation, discussion, conclusion, n, paperTitle }) {
  const today = new Date().toISOString().slice(0, 10);
  const title = (paperTitle || mainRq.replace(/\?$/, '')).slice(0, 140);
  return `# ${title}

*Generated by Probe · ${today}*

> **Note.** Findings reported below were produced by a simulated AI pilot with N=${n} synthetic participants. Treat as scaffolding for a real study, not as evidence.

## Abstract
This work investigates: *${mainRq}* The study integrates ${selectedBranches.length} sub-question${selectedBranches.length === 1 ? '' : 's'} under a unified ${chosenDesign?.name || 'mixed-methods'} design (${chosenDesign?.duration || '—'}).

## Research questions
${selectedBranches.map((r) => `- **RQ ${r.letter} (${r.angle}).** ${r.rq}`).join('\n')}

## Method
**Design.** ${chosenDesign?.summary || chosenDesign?.name || '—'}
**Components.** ${(chosenDesign?.components || []).map((c) => c.name).join(' · ') || '—'}
**Recruitment.** ${plan?.recruitment || '—'}
**Timeline.** ${plan?.timeline || '—'}

### Phases
${(plan?.phases || []).map((p, i) => `${i + 1}. **${p.name}** (${p.weeks}w) — ${p.detail}`).join('\n')}

## Findings
${evaluation}

## Discussion
${discussion}

## Conclusion
${conclusion}

## Threats to validity
- Simulated pilot, not real data
- Self-report focus measures susceptible to ceiling effects
- Convenience sample of telemetry-willing participants

## Ethics
IRB-light approval; opt-in telemetry; right to withdraw; aggregate-only external reporting.
`;
}

function composeLatex(input) {
  const { mainRq, selectedBranches, chosenDesign, plan, evaluation, discussion, conclusion, n, paperTitle } = input;
  const esc = (s) => String(s || '').replace(/[\\&%$#_{}~^]/g, (c) => '\\' + c).replace(/</g, '\\textless ').replace(/>/g, '\\textgreater ');
  const titleTex = esc(paperTitle || mainRq.replace(/\?$/, ''));
  return `\\documentclass[11pt]{article}
% arXiv-friendly preamble
\\usepackage[margin=1in]{geometry}
\\usepackage{times}
\\usepackage{microtype}
\\usepackage{authblk}
\\usepackage{hyperref}
\\usepackage{enumitem}

\\title{${titleTex}}
\\author{Anonymous Author(s)\\thanks{Generated with Probe.}}
\\affil{}
\\date{\\today}

\\begin{document}
\\maketitle

\\begin{abstract}
This work investigates: \\emph{${esc(mainRq)}} The study integrates ${selectedBranches.length} sub-question${selectedBranches.length === 1 ? '' : 's'} under a unified ${esc(chosenDesign?.name || 'mixed-methods')} design (${esc(chosenDesign?.duration || '--')}). Findings reported are from a simulated AI pilot with $N=${n}$ synthetic participants and should be treated as scaffolding for a real study.
\\end{abstract}

\\section{Research Questions}
\\begin{itemize}[leftmargin=*]
${selectedBranches.map((r) => `  \\item \\textbf{RQ ${r.letter} (${esc(r.angle)}).} ${esc(r.rq)}`).join('\n')}
\\end{itemize}

\\section{Method}
\\paragraph{Design.} ${esc(chosenDesign?.summary || chosenDesign?.name || '--')}
\\paragraph{Components.} ${esc((chosenDesign?.components || []).map((c) => c.name).join(' \\textbullet{} ') || '--')}
\\paragraph{Recruitment.} ${esc(plan?.recruitment || '--')}
\\paragraph{Timeline.} ${esc(plan?.timeline || '--')}

\\subsection{Phases}
\\begin{enumerate}[leftmargin=*]
${(plan?.phases || []).map((p) => `  \\item \\textbf{${esc(p.name)}} (${p.weeks}w) --- ${esc(p.detail)}`).join('\n')}
\\end{enumerate}

\\section{Findings}
${esc(evaluation).replace(/\n\n/g, '\n\n').replace(/\n/g, '\n\n')}

\\section{Discussion}
${esc(discussion).replace(/\n/g, '\n\n')}

\\section{Conclusion}
${esc(conclusion).replace(/\n/g, '\n\n')}

\\section*{Threats to Validity}
Simulated pilot, not real data. Self-report focus measures susceptible to ceiling effects. Convenience sample of telemetry-willing participants.

\\section*{Ethics}
IRB-light approval; opt-in telemetry; right to withdraw; aggregate-only external reporting.

\\end{document}
`;
}

function composeProjectPage(input) {
  const { mainRq, selectedBranches, chosenDesign, plan, evaluation, discussion, conclusion, n, paperTitle,
          teaserHtml, teaserCaption } = input;
  const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const title = esc(paperTitle || mainRq.replace(/\?$/, ''));
  const tagline = `A ${esc(chosenDesign?.name || 'mixed-methods')} study${chosenDesign?.duration ? ' over ' + esc(chosenDesign.duration) : ''}.`;
  const para = (s) => esc(s).split(/\n\n+/).map((p) => `<p>${p.replace(/\n/g, '<br/>')}</p>`).join('\n');
  const today = new Date().getFullYear();

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><title>${title}</title>
<style>
  :root { --ink: #1a1f2c; --ink2: #4a5160; --ink3: #8b93a3; --rule: #e6e3dc;
          --bg: #fbf8f1; --paper: #fff; --accent: #b04a3a; --warm: #d9a548; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--bg); color: var(--ink);
    font-family: 'Charter', Georgia, 'Times New Roman', serif; line-height: 1.65; -webkit-font-smoothing: antialiased; }
  .nav { padding: 16px 32px; border-bottom: 1px solid var(--rule);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 13px; color: var(--ink3); display: flex; align-items: center; gap: 16px; }
  .nav .brand { color: var(--accent); font-weight: 600; letter-spacing: 0.04em; }
  .hero { max-width: 880px; margin: 0 auto; padding: 72px 32px 24px; text-align: center; }
  .badge { display: inline-block; padding: 4px 12px; border: 1px solid var(--accent); color: var(--accent);
    font-family: ui-monospace, monospace; font-size: 11px; letter-spacing: 0.16em;
    text-transform: uppercase; border-radius: 999px; margin-bottom: 22px; }
  h1.title { font-size: 44px; line-height: 1.2; font-weight: 600; letter-spacing: -0.01em;
    margin: 0 0 16px; color: var(--ink); }
  .tagline { font-size: 19px; color: var(--ink2); margin: 0 auto 32px; max-width: 720px; }
  .authors { font-family: -apple-system, sans-serif; font-size: 14px; color: var(--ink2);
    display: flex; justify-content: center; flex-wrap: wrap; gap: 8px 22px; margin-bottom: 8px; }
  .authors .a { white-space: nowrap; }
  .affil { font-family: -apple-system, sans-serif; font-size: 12px; color: var(--ink3); margin-bottom: 28px; }
  .actions { display: flex; justify-content: center; gap: 10px; flex-wrap: wrap; margin-bottom: 16px;
    font-family: -apple-system, sans-serif; }
  .actions a { display: inline-flex; align-items: center; gap: 8px;
    padding: 9px 18px; background: var(--ink); color: var(--paper);
    text-decoration: none; border-radius: 999px; font-size: 13px; font-weight: 500; cursor: pointer; }
  .actions a.ghost { background: transparent; color: var(--ink); border: 1px solid var(--ink); }
  .teaser { max-width: 980px; margin: 32px auto; padding: 0 32px; }
  .teaser .frame { background: var(--paper); border: 1px solid var(--rule);
    border-radius: 8px; padding: 48px 32px; min-height: 320px;
    display: flex; align-items: center; justify-content: center; flex-direction: column; gap: 18px;
    box-shadow: 0 1px 0 rgba(0,0,0,0.02); position: relative; overflow: hidden; }
  .teaser .frame::before { content: ''; position: absolute; inset: 0;
    background: radial-gradient(circle at 30% 20%, rgba(217,165,72,0.10), transparent 60%),
                radial-gradient(circle at 80% 80%, rgba(176,74,58,0.08), transparent 55%); }
  .teaser .glyph { width: 96px; height: 96px; border-radius: 50%;
    background: linear-gradient(135deg, var(--warm), var(--accent));
    box-shadow: 0 8px 32px -8px rgba(176,74,58,0.4); position: relative; z-index: 1; }
  .teaser .cap { font-family: -apple-system, sans-serif; font-size: 12px; color: var(--ink3);
    letter-spacing: 0.06em; position: relative; z-index: 1; }
  section { max-width: 800px; margin: 0 auto; padding: 32px; }
  h2 { font-family: -apple-system, sans-serif; font-size: 22px; font-weight: 600;
    color: var(--ink); margin: 24px 0 14px; letter-spacing: -0.01em; }
  h3 { font-family: -apple-system, sans-serif; font-size: 16px; font-weight: 600;
    color: var(--ink); margin: 22px 0 8px; }
  p { font-size: 17px; color: var(--ink); margin: 0 0 14px; }
  .small { font-family: -apple-system, sans-serif; font-size: 13px; color: var(--ink3); }
  .rqs { display: grid; gap: 12px; padding: 0; list-style: none; margin: 14px 0; }
  .rqs li { padding: 14px 18px; background: var(--paper); border: 1px solid var(--rule);
    border-left: 4px solid var(--warm); border-radius: 4px; font-size: 16px; }
  .rqs li b { font-family: -apple-system, sans-serif; color: var(--accent); margin-right: 8px; }
  .grid3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 14px; margin: 16px 0; }
  .grid3 .card { background: var(--paper); border: 1px solid var(--rule); border-radius: 6px; padding: 16px;
    font-family: -apple-system, sans-serif; font-size: 14px; }
  .grid3 .card .lab { font-size: 11px; color: var(--accent); letter-spacing: 0.12em;
    text-transform: uppercase; margin-bottom: 6px; }
  .grid3 .card .val { font-size: 22px; font-weight: 600; color: var(--ink); }
  .quote { background: var(--paper); border-left: 4px solid var(--accent);
    padding: 18px 22px; margin: 18px 0; font-style: italic; color: var(--ink2); border-radius: 0 4px 4px 0; }
  .bib { background: var(--paper); border: 1px solid var(--rule); border-radius: 4px;
    padding: 16px 18px; font-family: ui-monospace, monospace; font-size: 12px;
    color: var(--ink2); white-space: pre; overflow-x: auto; line-height: 1.55; }
  footer { max-width: 800px; margin: 0 auto; padding: 48px 32px;
    border-top: 1px solid var(--rule); font-family: -apple-system, sans-serif;
    font-size: 12px; color: var(--ink3); text-align: center; }
  footer .sim { display: inline-block; padding: 4px 10px; background: rgba(176,74,58,0.08);
    color: var(--accent); border-radius: 3px; font-weight: 600; letter-spacing: 0.04em; }
</style></head><body>
<div class="nav"><span class="brand">probe.</span><span>generated project page · preview</span></div>

<div class="hero">
  <div class="badge">${esc(chosenDesign?.name || 'study')}</div>
  <h1 class="title">${title}</h1>
  <p class="tagline">${tagline}</p>
  <div class="authors">
    <span class="a">Author One</span>
    <span class="a">Author Two</span>
    <span class="a">Author Three</span>
  </div>
  <div class="affil">Your Lab · ${today}</div>
  <div class="actions">
    <a>📄 paper</a>
    <a class="ghost">⚡ arXiv</a>
    <a class="ghost">▶ video</a>
    <a class="ghost">⌬ code</a>
    <a class="ghost">✦ data</a>
  </div>
</div>

<div class="teaser"><div class="frame">
  ${teaserHtml
    ? `<div style="width:100%; height:auto; max-height:380px; display:flex; align-items:center; justify-content:center; position:relative; z-index:1;">${teaserHtml}</div>
       <div class="cap">${esc(teaserCaption || 'figure generated by Claude · edit before publishing')}</div>`
    : `<div class="glyph"></div>
       <div class="cap">teaser figure · drop your hero artifact here</div>`}
</div></div>

<section>
  <h2>Abstract</h2>
  <p>This work investigates: <em>${esc(mainRq)}</em> The study integrates ${selectedBranches.length} sub-question${selectedBranches.length === 1 ? '' : 's'} under a unified ${esc(chosenDesign?.name || 'mixed-methods')} design${chosenDesign?.duration ? ' running ' + esc(chosenDesign.duration) : ''}.</p>
  <p class="small">Findings shown on this page were produced by a simulated AI pilot with N=${n} synthetic participants. This is a preview of how the published page will look — replace placeholders with real material before sharing.</p>
</section>

<section>
  <h2>Research questions</h2>
  <ul class="rqs">
    ${selectedBranches.map((r) => `<li><b>RQ ${esc(r.letter)} · ${esc(r.angle)}.</b> ${esc(r.rq)}</li>`).join('\n    ')}
  </ul>
</section>

<section>
  <h2>Method</h2>
  <p>${esc(chosenDesign?.summary || chosenDesign?.name || '—')}</p>
  <div class="grid3">
    <div class="card"><div class="lab">design</div><div class="val">${esc(chosenDesign?.name || '—')}</div></div>
    <div class="card"><div class="lab">duration</div><div class="val">${esc(chosenDesign?.duration || '—')}</div></div>
    <div class="card"><div class="lab">participants</div><div class="val">${n}</div></div>
  </div>
  <h3>Phases</h3>
  <ol>
    ${(plan?.phases || []).map((p) => `<li><b>${esc(p.name)}</b> (${p.weeks}w) — ${esc(p.detail)}</li>`).join('\n    ')}
  </ol>
</section>

<section>
  <h2>Findings</h2>
  ${para(evaluation)}
</section>

<section>
  <h2>Discussion</h2>
  ${para(discussion)}
</section>

<section>
  <h2>Conclusion</h2>
  ${para(conclusion)}
</section>

<section>
  <h2>BibTeX</h2>
  <div class="bib">@inproceedings{author${today},
  title  = {${title.replace(/[{}]/g, '')}},
  author = {Author One and Author Two and Author Three},
  year   = {${today}},
  note   = {Preprint},
}</div>
</section>

<footer>
  <p><span class="sim">! SIMULATED PILOT</span> &nbsp; This page is a forward-looking preview generated by Probe. Replace synthetic findings, authors, and links with real material before publishing.</p>
  <p>Inspired by the Nerfies / academic project page template.</p>
</footer>
</body></html>`;
}

// Inline PDF: open a print-ready HTML in a popup window the user can save as PDF.
function openPrintablePdf(md, title) {
  // Minimal markdown → HTML: headings, paragraphs, lists, bold/italic.
  const html = mdToHtml(md);
  const w = window.open('', '_blank', 'width=820,height=1100');
  if (!w) return false;
  w.document.write(`<!doctype html>
<html><head><title>${title}</title>
<style>
  @page { size: letter; margin: 1in; }
  body { font: 11pt/1.55 Georgia, 'Times New Roman', serif; color: #111; max-width: 6.5in; margin: auto; }
  h1 { font-size: 22pt; margin: 0 0 6pt; }
  h2 { font-size: 14pt; margin: 18pt 0 6pt; border-bottom: 1px solid #ccc; padding-bottom: 3pt; }
  h3 { font-size: 12pt; margin: 14pt 0 4pt; }
  p, li { font-size: 11pt; }
  blockquote { border-left: 3px solid #d9a548; padding: 2pt 12pt; color: #555; font-style: italic; margin: 12pt 0; background: #faf6ed; }
  em { color: #333; }
  hr { border: none; border-top: 1px solid #ccc; margin: 18pt 0; }
  ul, ol { padding-left: 22pt; }
  .stamp { color: #888; font-size: 9pt; margin-top: -2pt; }
</style></head><body>${html}
<script>setTimeout(() => window.print(), 300);</script>
</body></html>`);
  w.document.close();
  return true;
}

function mdToHtml(md) {
  const lines = md.split('\n');
  const out = [];
  let inList = false; let listType = '';
  const closeList = () => { if (inList) { out.push(listType === 'ol' ? '</ol>' : '</ul>'); inList = false; } };
  const inline = (s) => s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>');

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) { closeList(); out.push(''); continue; }
    if (line.startsWith('# ')) { closeList(); out.push(`<h1>${inline(line.slice(2))}</h1>`); continue; }
    if (line.startsWith('## ')) { closeList(); out.push(`<h2>${inline(line.slice(3))}</h2>`); continue; }
    if (line.startsWith('### ')) { closeList(); out.push(`<h3>${inline(line.slice(4))}</h3>`); continue; }
    if (line.startsWith('> ')) { closeList(); out.push(`<blockquote>${inline(line.slice(2))}</blockquote>`); continue; }
    const ol = line.match(/^(\d+)\.\s+(.*)/);
    if (ol) { if (!inList || listType !== 'ol') { closeList(); out.push('<ol>'); inList = true; listType = 'ol'; } out.push(`<li>${inline(ol[2])}</li>`); continue; }
    if (line.startsWith('- ')) { if (!inList || listType !== 'ul') { closeList(); out.push('<ul>'); inList = true; listType = 'ul'; } out.push(`<li>${inline(line.slice(2))}</li>`); continue; }
    closeList();
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  return out.join('\n');
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function Report({ mainRq, selectedBranches, chosenDesign, plan, evalResult, onBack, onDone, goTo }) {
  const { evaluation = '', personas = [], n = 0 } = evalResult || {};
  const [discussion, setDiscussion] = useState(() => defaultDiscussion(selectedBranches));
  const [conclusion, setConclusion] = useState(() => defaultConclusion(selectedBranches));
  const titleOptions = React.useMemo(() => generateTitles(mainRq, chosenDesign), [mainRq, chosenDesign?.id]);
  const [titles, setTitles] = useState(titleOptions);
  const [titleIdx, setTitleIdx] = useState(0);
  const [editingTitleIdx, setEditingTitleIdx] = useState(null);
  const [editing, setEditing] = useState(null); // 'disc' | 'conc'
  const [stage, setStage] = useState(0); // 0 drafting, 1 ready
  const [toast, setToast] = useState('');
  const [namePrompt, setNamePrompt] = useState(null); // { kind: 'save'|'saveOpen' } | null
  const [projectName, setProjectName] = useState(() => suggestProjectName(mainRq));

  useEffect(() => {
    const t = setTimeout(() => setStage(1), 1100);
    // Fire LLM call to replace stock titles + discussion + conclusion.
    // Findings come from the evaluation stage; if absent, the API will
    // produce reasonable text from the plan + design alone.
    const findings = (evalResult && evalResult.findings) || [];
    fetch('/api/probe/report', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        premise: mainRq,
        rqs: selectedBranches,
        designName: (chosenDesign && chosenDesign.name) || 'integrated study',
        findings,
      }),
    })
      .then((r) => r.ok ? r.json() : null)
      .then((data) => {
        if (!data) return;
        if (Array.isArray(data.titleOptions) && data.titleOptions.length) {
          setTitles(data.titleOptions.slice(0, 3));
        }
        if (data.discussion) setDiscussion(data.discussion);
        if (data.conclusion) setConclusion(data.conclusion);
      })
      .catch(() => { /* keep stock content */ });
    return () => clearTimeout(t);
  }, []);

  // Hotkeys
  useEffect(() => {
    const onKey = (e) => {
      const tag = (e.target && e.target.tagName) || '';
      if (tag === 'INPUT' || tag === 'TEXTAREA') return;
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      if (e.key === 'Escape') { e.preventDefault(); if (editing) setEditing(null); else onBack(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [editing]);

  const flash = (msg) => { setToast(msg); setTimeout(() => setToast(''), 1800); };

  const reportInput = { mainRq, selectedBranches, chosenDesign, plan,
    evaluation, discussion, conclusion, n, paperTitle: titles[titleIdx] || mainRq };

  const onMd = () => {
    const md = composeMarkdown(reportInput);
    downloadBlob('probe-report.md', new Blob([md], { type: 'text/markdown' }));
    flash('saved · probe-report.md');
  };
  const onTex = () => {
    const tex = composeLatex(reportInput);
    downloadBlob('probe-report.tex', new Blob([tex], { type: 'text/x-tex' }));
    flash('saved · probe-report.tex (arXiv)');
  };
  const onPdf = () => {
    const md = composeMarkdown(reportInput);
    const ok = openPrintablePdf(md, 'probe-report');
    flash(ok ? 'opened · use cmd/ctrl+p to save as PDF' : 'popup blocked — allow popups to export PDF');
  };
  const onProjectPage = () => {
    // First try to fetch a generated teaser SVG from /api/probe/teaser.
    // Render the project page either way — if the teaser fetch errors,
    // composeProjectPage falls back to the original placeholder glyph.
    flash('drafting teaser figure with Claude…');
    fetch('/api/probe/teaser', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        premise: mainRq,
        paperTitle: titles[titleIdx] || mainRq,
        designName: chosenDesign?.name || 'integrated study',
        rqs: selectedBranches || [],
      }),
    })
      .then((r) => r.ok ? r.json() : null)
      .catch(() => null)
      .then((data) => {
        const teaserHtml = data && data.svg
          ? `<div class="teaser-svg" style="position:relative;width:100%;height:100%;">${data.svg}</div>`
          : null;
        const teaserCaption = (data && data.caption) || null;
        const html = composeProjectPage({ ...reportInput, teaserHtml, teaserCaption });
        const w = window.open('', '_blank', 'width=1100,height=900');
        if (!w) { flash('popup blocked — allow popups to preview project page'); return; }
        w.document.write(html); w.document.close();
        flash(teaserHtml
          ? '✓ project page opened — teaser figure generated by Claude'
          : 'project page opened (teaser fallback — Claude API unavailable)');
      });
  };
  const onSave = () => setNamePrompt({ kind: 'save' });
  const onSaveOpen = () => setNamePrompt({ kind: 'saveOpen' });
  const confirmSave = () => {
    const safeName = (projectName || 'probe-project').trim().replace(/[^a-z0-9-_]+/gi, '-').replace(/^-+|-+$/g, '') || 'probe-project';
    const md = composeMarkdown({ ...reportInput, projectName });
    downloadBlob(`${safeName}.md`, new Blob([md], { type: 'text/markdown' }));
    flash(`saved · ${safeName}.md`);
    const kind = namePrompt?.kind;
    setNamePrompt(null);
    if (kind === 'saveOpen') setTimeout(() => onDone && onDone({ projectName: safeName }), 400);
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Crumb steps={[
        ['probe', palette.amber, 'probe'],
        ['new project', palette.ink2, 'new project'],
        ['brainstorm', palette.ink2, 'brainstorm'],
        ['literature', palette.ink2, 'literature'],
        ['methodology', palette.ink2, 'methodology'],
        ['artifacts', palette.ink2, 'artifacts'],
        ['evaluation', palette.ink2, 'evaluation'],
        ['report', palette.ink, 'report'],
      ]} onStepClick={goTo}
      right={
        <span style={{ display: 'flex', gap: 14, alignItems: 'center' }}>
          <span style={{ color: palette.ink3 }}>stage 6 · report</span>
          <button onClick={onBack} style={ghostBtnStyle}><kbd style={kbdStyle}>esc</kbd> back</button>
        </span>
      } />

      <div style={{ flex: 1, padding: '28px 32px 100px', maxWidth: 1100, margin: '0 auto', width: '100%' }}>
        <div style={{ color: palette.ink3, fontSize: 11, letterSpacing: '0.14em',
          textTransform: 'uppercase', marginBottom: 8 }}>
          ─── report · discussion · conclusion · export ───
        </div>
        <h2 style={{ fontSize: 18, fontWeight: 500, margin: 0, color: palette.ink2 }}>
          Probe drafted the discussion and conclusion off your findings. Edit anything, then export.
        </h2>

        {stage === 0 ? (
          <>
            {window.ModelStatusLine && (
              <div className="fade-in" style={{ padding: '14px 0 6px' }}>
                <window.ModelStatusLine
                  model="claude-sonnet-4-6"
                  phase={window.PhaseDots ? (
                    <window.PhaseDots
                      phases={['planning', 'drafting', 'citing', 'polishing']}
                      activeIdx={1}
                      accent={palette.amber}
                      compact
                    />
                  ) : null}
                  accent={palette.amber}
                  running
                />
              </div>
            )}
            <DraftingRow />
          </>
        ) : (
          <div className="fade-in" style={{ marginTop: 22 }}>
            <SectionHeader title="paper title" hint="pick one · edit it · or write your own" />
            <TitlePicker titles={titles} setTitles={setTitles}
              titleIdx={titleIdx} setTitleIdx={setTitleIdx}
              editingTitleIdx={editingTitleIdx} setEditingTitleIdx={setEditingTitleIdx}
              onRegenerate={() => setTitles(generateTitles(mainRq, chosenDesign, true))} />

            <SectionEditable label="discussion" hint="implications · threats to validity · ethics"
              value={discussion} setValue={setDiscussion}
              isEditing={editing === 'disc'} setEditing={(v) => setEditing(v ? 'disc' : null)} />

            <SectionEditable label="conclusion" hint="contributions · future work"
              value={conclusion} setValue={setConclusion}
              isEditing={editing === 'conc'} setEditing={(v) => setEditing(v ? 'conc' : null)} />

            <SectionHeader title="export" hint="markdown · latex (arXiv) · pdf via print" />

            <div style={{
              padding: '14px 16px', background: palette.bg2,
              border: `1px solid ${palette.rule}`, borderRadius: 4,
              display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap',
            }}>
              <ExportBtn label="markdown"     hint=".md · plain text"      onClick={onMd} accent={palette.amber} />
              <ExportBtn label="latex"        hint=".tex · arXiv preamble" onClick={onTex} accent={palette.cyan} />
              <ExportBtn label="pdf"          hint="renders md → print"    onClick={onPdf} accent={palette.moss} />
              <ExportBtn label="project page" hint="academic-style preview" onClick={onProjectPage} accent={palette.rose} />
            </div>
          </div>
        )}
      </div>

      {namePrompt && (
        <NameProjectModal name={projectName} setName={setProjectName}
          kind={namePrompt.kind}
          suggestion={suggestProjectName(mainRq)}
          onCancel={() => setNamePrompt(null)} onConfirm={confirmSave} />
      )}

      {/* footer */}
      <div style={{
        position: 'sticky', bottom: 0, background: palette.bg,
        borderTop: `1px solid ${palette.rule}`,
        padding: '10px 22px', display: 'flex', alignItems: 'center', gap: 14,
        color: palette.ink3, fontSize: 12.5,
      }}>
        {toast ? (
          <span style={{ color: palette.moss }}>✓ {toast}</span>
        ) : (
          <span><kbd style={kbdStyle}>esc</kbd> back · use export buttons above to download</span>
        )}
        <span style={{ marginLeft: 'auto', display: 'flex', gap: 10, alignItems: 'center' }}>
          <button disabled={stage < 1} onClick={onSave} style={{
            background: 'transparent', color: palette.ink2,
            border: `1px solid ${palette.rule}`,
            padding: '5px 14px', borderRadius: 3, fontFamily: 'inherit', fontSize: 12, cursor: stage < 1 ? 'not-allowed' : 'pointer',
            opacity: stage < 1 ? 0.5 : 1,
          }}>save</button>
          <button disabled={stage < 1} onClick={onSaveOpen} style={{
            background: stage < 1 ? 'transparent' : palette.amber,
            color: stage < 1 ? palette.ink4 : palette.bg,
            border: `1px solid ${stage < 1 ? palette.rule : palette.amber}`,
            padding: '5px 14px', borderRadius: 3, fontFamily: 'inherit', fontSize: 12, fontWeight: 600,
            cursor: stage < 1 ? 'not-allowed' : 'pointer',
            display: 'inline-flex', alignItems: 'center', gap: 8,
          }}>
            save and open project
            <kbd style={{ ...kbdStyle, background: stage < 1 ? palette.bg2 : 'rgba(0,0,0,0.2)',
              color: stage < 1 ? palette.ink4 : 'rgba(0,0,0,0.7)',
              borderColor: stage < 1 ? palette.rule : 'rgba(0,0,0,0.15)' }}>↵</kbd>
          </button>
        </span>
      </div>
    </div>
  );
}

// ─── Title generation + picker ───
function generateTitles(rq, design, shuffle) {
  const stop = new Set(['the','a','an','of','in','on','for','to','and','or','is','are','do','does','how','what','why','which','that','their','they','it','its','as','with','by','from','during','can','will','should']);
  const words = (rq || '').toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/\s+/).filter((w) => w && !stop.has(w));
  const noun = words.slice(0, 3).join(' ') || 'the question';
  const Cap = (s) => s.replace(/\b\w/g, (c) => c.toUpperCase());
  const designKind = (design?.name || '').toLowerCase();
  const venuePool = ['Field Study', 'Mixed-Methods Investigation', 'Diary Study',
    'Pre-Registered Trial', 'Multi-Site Inquiry'];
  const venue = venuePool[(shuffle ? Math.floor(Math.random() * venuePool.length) : 0)];

  // Three distinct title voices: punchy / academic-formal / quote-led
  return [
    `Threading the Day: ${Cap(noun)} in Remote Knowledge Work`,
    `Toward an Integrated Account of ${Cap(noun)}: A ${venue}`,
    `"It's the slope, not the cliff": Lived Experience of ${Cap(noun)}`,
  ];
}

function TitlePicker({ titles, setTitles, titleIdx, setTitleIdx,
                      editingTitleIdx, setEditingTitleIdx, onRegenerate }) {
  const [draft, setDraft] = useState('');
  const updateAt = (i, val) => setTitles((t) => t.map((x, k) => k === i ? val : x));
  return (
    <div style={{
      padding: '14px 16px', background: palette.bg2,
      border: `1px solid ${palette.rule}`, borderRadius: 4,
      display: 'flex', flexDirection: 'column', gap: 8,
    }}>
      {titles.map((t, i) => {
        const sel = i === titleIdx;
        const isEditing = editingTitleIdx === i;
        return (
          <div key={i} style={{
            padding: '10px 12px',
            border: `1px solid ${sel ? palette.amber : palette.rule}`,
            borderLeft: `3px solid ${sel ? palette.amber : palette.ink4}`,
            background: sel ? 'rgba(217,165,72,0.08)' : palette.bg,
            borderRadius: 3, display: 'flex', alignItems: 'center', gap: 10,
          }}>
            <span style={{ ...kbdStyle, color: sel ? palette.amber : palette.ink3,
              borderColor: sel ? palette.amber : palette.rule }}>{i + 1}</span>
            {isEditing ? (
              <input value={draft} onChange={(e) => setDraft(e.target.value)} autoFocus
                onKeyDown={(e) => {
                  if (e.key === 'Enter') { updateAt(i, draft.trim() || titles[i]); setEditingTitleIdx(null); setTitleIdx(i); }
                  if (e.key === 'Escape') { setEditingTitleIdx(null); }
                }}
                style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none',
                  color: palette.ink, fontFamily: 'inherit', fontSize: 14, caretColor: palette.amber }} />
            ) : (
              <span onClick={() => setTitleIdx(i)} style={{
                flex: 1, cursor: 'pointer', color: sel ? palette.ink : palette.ink2,
                fontSize: 14, lineHeight: 1.45,
              }}>{t}</span>
            )}
            {!isEditing ? (
              <>
                <button onClick={() => { setDraft(t); setEditingTitleIdx(i); }} style={reportIconBtn()}>edit</button>
                {sel && <span style={{ color: palette.amber, fontSize: 11, marginLeft: 4 }}>● picked</span>}
              </>
            ) : (
              <button onClick={() => { updateAt(i, draft.trim() || titles[i]); setEditingTitleIdx(null); setTitleIdx(i); }} style={reportIconBtn()}>save</button>
            )}
          </div>
        );
      })}
      <div style={{ display: 'flex', gap: 8, marginTop: 4 }}>
        <button onClick={onRegenerate} style={reportIconBtn()}>↻ regenerate</button>
        <button onClick={() => {
          setTitles((t) => [...t, 'Untitled']);
          setTitleIdx(titles.length);
          setDraft('Untitled');
          setEditingTitleIdx(titles.length);
        }} style={reportIconBtn()}>+ write your own</button>
      </div>
    </div>
  );
}

function suggestProjectName(rq) {
  const stop = new Set(['the','a','an','of','in','on','for','to','and','or','is','are','do','does','how','what','why','which','that','their','they','it','its','as','with','by','from','during','long','can','will','should']);
  const words = (rq || '').toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/\s+/).filter((w) => w && !stop.has(w));
  const top = words.slice(0, 4).join('-') || 'probe-project';
  return top.slice(0, 40);
}

function NameProjectModal({ name, setName, kind, suggestion, onCancel, onConfirm }) {
  const inputRef = React.useRef(null);
  useEffect(() => { inputRef.current && inputRef.current.focus(); inputRef.current && inputRef.current.select(); }, []);
  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'Escape') { e.preventDefault(); onCancel(); }
      if (e.key === 'Enter')  { e.preventDefault(); if (name.trim()) onConfirm(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [name]);
  return (
    <div style={{
      position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)', zIndex: 50,
      display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24,
    }} onClick={onCancel}>
      <div onClick={(e) => e.stopPropagation()} style={{
        width: 460, maxWidth: '100%', background: palette.bg2,
        border: `1px solid ${palette.rule}`, borderLeft: `3px solid ${palette.amber}`,
        borderRadius: 4, padding: '20px 22px',
      }}>
        <div style={{ color: palette.amber, fontSize: 11, letterSpacing: '0.14em',
          textTransform: 'uppercase', fontWeight: 600, marginBottom: 4 }}>name your project</div>
        <div style={{ color: palette.ink3, fontSize: 12, marginBottom: 14 }}>
          Probe suggested <span style={{ color: palette.ink2 }}>{suggestion}</span> from your research question. Edit it, or use your own.
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8,
          padding: '10px 12px', background: palette.bg, border: `1px solid ${palette.rule}`, borderRadius: 3 }}>
          <span style={{ color: palette.amber, fontWeight: 600 }}>›</span>
          <input ref={inputRef} value={name} onChange={(e) => setName(e.target.value)}
            placeholder={suggestion}
            style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none',
              color: palette.ink, fontFamily: 'inherit', fontSize: 14, caretColor: palette.amber }} />
          <span style={{ color: palette.ink3, fontSize: 11 }}>.md</span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 16 }}>
          <button onClick={() => setName(suggestion)} style={{
            background: 'transparent', border: 'none', color: palette.ink3, fontFamily: 'inherit',
            fontSize: 11, cursor: 'pointer', textDecoration: 'underline',
          }}>use suggestion</button>
          <span style={{ display: 'flex', gap: 8 }}>
            <button onClick={onCancel} style={{
              background: 'transparent', border: `1px solid ${palette.rule}`, color: palette.ink2,
              padding: '5px 12px', borderRadius: 3, fontFamily: 'inherit', fontSize: 12, cursor: 'pointer',
            }}><kbd style={kbdStyle}>esc</kbd> cancel</button>
            <button onClick={onConfirm} disabled={!name.trim()} style={{
              background: !name.trim() ? 'transparent' : palette.amber,
              color: !name.trim() ? palette.ink4 : palette.bg,
              border: `1px solid ${!name.trim() ? palette.rule : palette.amber}`,
              padding: '5px 12px', borderRadius: 3, fontFamily: 'inherit', fontSize: 12, fontWeight: 600,
              cursor: !name.trim() ? 'not-allowed' : 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6,
            }}>
              {kind === 'saveOpen' ? 'save and open' : 'save'}
              <kbd style={{ ...kbdStyle, background: !name.trim() ? palette.bg2 : 'rgba(0,0,0,0.2)',
                color: !name.trim() ? palette.ink4 : 'rgba(0,0,0,0.7)',
                borderColor: !name.trim() ? palette.rule : 'rgba(0,0,0,0.15)' }}>↵</kbd>
            </button>
          </span>
        </div>
      </div>
    </div>
  );
}

function ExportBtn({ label, hint, onClick, accent }) {
  return (
    <button onClick={onClick} style={{
      flex: '0 0 auto', minWidth: 180, padding: '10px 14px', textAlign: 'left',
      background: palette.bg, border: `1px solid ${palette.rule}`,
      borderLeft: `3px solid ${accent}`, borderRadius: 3,
      color: palette.ink, fontFamily: 'inherit', cursor: 'pointer',
      display: 'flex', flexDirection: 'column', gap: 2,
    }}
      onMouseEnter={(e) => { e.currentTarget.style.borderColor = accent; e.currentTarget.style.borderLeftColor = accent; }}
      onMouseLeave={(e) => { e.currentTarget.style.borderColor = palette.rule; e.currentTarget.style.borderLeftColor = accent; }}>
      <span style={{ color: accent, fontSize: 13, fontWeight: 600, letterSpacing: '0.02em' }}>{label}</span>
      <span style={{ color: palette.ink3, fontSize: 11 }}>{hint}</span>
    </button>
  );
}

function DraftingRow() {
  return (
    <div style={{
      marginTop: 22, padding: '14px 16px',
      background: palette.bg2, border: `1px solid ${palette.rule}`, borderRadius: 4,
    }}>
      <div style={{ color: palette.ink3, fontSize: 11, letterSpacing: '0.12em',
        textTransform: 'uppercase', marginBottom: 10 }}>writing</div>
      {['drafting discussion · implications + threats to validity', 'drafting conclusion · contributions + future work', 'composing report skeleton'].map((t, i) => (
        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10,
          padding: '6px 0', color: palette.ink2, fontSize: 13 }}>
          <span className="pulse-dot" style={{ color: palette.amber, fontSize: 14 }}>●</span>
          <span>{t}</span>
        </div>
      ))}
    </div>
  );
}

function SectionEditable({ label, hint, value, setValue, isEditing, setEditing }) {
  return (
    <div className="fade-in" style={{ marginTop: 28 }}>
      <SectionHeader title={label} hint={hint} />
      <div style={{
        padding: '14px 16px', background: palette.bg2,
        border: `1px solid ${palette.rule}`, borderLeft: `3px solid ${palette.amber}`,
        borderRadius: 4,
      }}>
        <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 8, gap: 6 }}>
          {isEditing ? (
            <button onClick={() => setEditing(false)} style={reportIconBtn()}>done</button>
          ) : (
            <button onClick={() => setEditing(true)} style={reportIconBtn()}>edit</button>
          )}
        </div>
        {isEditing ? (
          <textarea value={value} onChange={(e) => setValue(e.target.value)}
            style={{
              width: '100%', minHeight: 200, boxSizing: 'border-box',
              background: palette.bg, color: palette.ink, fontFamily: 'inherit', fontSize: 13,
              border: `1px solid ${palette.rule}`, padding: '10px 12px', borderRadius: 3,
              outline: 'none', resize: 'vertical', lineHeight: 1.6, caretColor: palette.amber,
            }} />
        ) : (
          window.MarkdownText
            ? <window.MarkdownText text={value} />
            : <pre style={{
                margin: 0, color: palette.ink, fontFamily: 'inherit', fontSize: 13,
                lineHeight: 1.65, whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              }}>{value}</pre>
        )}
      </div>
    </div>
  );
}

function SectionHeader({ title, hint }) {
  return (
    <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, margin: '24px 0 10px' }}>
      <span style={{ color: palette.amber, fontSize: 11, letterSpacing: '0.14em',
        textTransform: 'uppercase', fontWeight: 600 }}>{title}</span>
      {hint && <span style={{ color: palette.ink3, fontSize: 11 }}>· {hint}</span>}
      <span style={{ flex: 1, borderBottom: `1px solid ${palette.rule}`, transform: 'translateY(-4px)' }} />
    </div>
  );
}

function Crumb({ steps, right, onStepClick }) {
  return (
    <div style={{
      padding: '14px 22px', display: 'flex', alignItems: 'center', gap: 12,
      borderBottom: `1px solid ${palette.rule}`, color: palette.ink3, fontSize: 12,
    }}>
      {steps.map((step, i) => {
        const [s, c, key] = step;
        const isLast = i === steps.length - 1;
        const clickable = !isLast && onStepClick;
        return (
          <React.Fragment key={i}>
            <span
              onClick={clickable ? () => onStepClick(key || s) : undefined}
              onMouseEnter={clickable ? (e) => { e.currentTarget.style.textDecoration = 'underline'; } : undefined}
              onMouseLeave={clickable ? (e) => { e.currentTarget.style.textDecoration = 'none'; } : undefined}
              style={{ color: c, cursor: clickable ? 'pointer' : 'default' }}
            >{s}</span>
            {i < steps.length - 1 && <span>›</span>}
          </React.Fragment>
        );
      })}
      <span style={{ marginLeft: 'auto' }}>{right}</span>
    </div>
  );
}

const reportIconBtn = () => ({
  background: 'transparent', border: `1px solid ${palette.rule}`, color: palette.ink2,
  fontFamily: 'inherit', fontSize: 11, padding: '3px 9px', borderRadius: 3, cursor: 'pointer',
});

window.Report = Report;
