/* global React */
const { useState, useEffect } = React;

// Stage 4 — Artifacts
// Adaptive: the artifact list is computed from the chosen design's components.
// Each artifact is a draft document the user can read, edit inline, copy, or download.

const palette = window.__probePalette;
const kbdStyle = window.__probeKbd;
const chipStyle = window.__probeChip;
const ghostBtnStyle = window.__probeGhostBtn;

// Decide which artifacts a given study plan needs.
// Heuristic: scan plan.phases + design components + design summary
// for keywords. If the keyword pass returns nothing (LLM-generated
// designs sometimes phrase the plan generically), fall back to the
// always-useful triplet so the user is never staring at a blank
// artifacts pane.
function decideArtifacts(plan, design) {
  const text = [
    ...(plan?.phases || []).map((p) => `${p.name} ${p.detail}`),
    ...(design?.components || []).map((c) => c.name),
    design?.summary || '',
    design?.name || '',
    plan?.recruitment || '',
  ].join(' ').toLowerCase();

  const wants = [];
  if (/(probe|instrument|build|deploy|widget|bot|software|tool|app|app-based|prototype|technology|platform)/.test(text)) {
    wants.push('impl');
  }
  if (/(interview|diary|esm|body-map|walkthrough|trial|ritual|session|field|qualitative|cohort|participant)/.test(text)) {
    wants.push('protocol');
  }
  if (/survey/.test(text)) wants.push('survey');
  if (/(diary|esm)/.test(text)) wants.push('diary');
  // Always include an IRB memo if any human contact exists
  if (/(participant|interview|diary|deploy|trial|survey|cohort|recruit)/.test(text)) wants.push('irb');

  // Fallback: if we matched nothing, ship the standard set so the
  // user never sees an empty artifact list.
  if (wants.length === 0) return ['impl', 'protocol', 'irb'];
  return wants;
}

const ARTIFACT_DEFS = {
  impl: {
    title: 'implementation plan',
    subtitle: 'agents.md · for handoff to a coding agent',
    kind: 'software',
    color: '#7fb069',
    filename: 'IMPLEMENTATION.md',
    body: (ctx) => `# Implementation plan
> Generated by Probe · stage 4 · hand this to a coding agent

## Project
${ctx.designName} — ${ctx.duration}

## Goal
Build the instrumented artifact described in the study design so it is ready for a 4–6 week field deployment.

## Scope (must-have)
- calendar-aware trigger (Google + Outlook OAuth)
- post-meeting prompt surface (Slack DM + desktop notification)
- 90-second guided ritual flow with skip/snooze
- self-rating capture (1–7 Likert) + free-text
- typing-cadence telemetry on opt-in (desktop helper, not browser)
- consent gate before any telemetry begins

## Out of scope
- mobile native app
- physiological sensors
- cross-org admin console

## Tech stack
- backend: TypeScript · Hono · Postgres · Drizzle
- jobs: Inngest (calendar webhook fan-out)
- frontend: React + Tailwind, Slack Block Kit for in-Slack UI
- desktop helper: Tauri (macOS + Windows) — opt-in only

## Data model
\`\`\`
participant(id, role, consent_at, tz, telemetry_opt_in)
meeting(id, participant_id, started_at, ended_at, attendees, agenda_present)
prompt(id, meeting_id, surfaced_at, completed, skipped, rating, free_text)
trace(id, participant_id, ts, key_events_per_min) -- only if telemetry_opt_in
\`\`\`

## Key flows
1. Participant onboards → consent → calendar OAuth → optional desktop helper.
2. Cron: every 5 min check calendars; for meetings ending in next 2 min, schedule a prompt.
3. Prompt fires; ritual recorded; rating + free-text persisted.
4. Weekly digest: aggregated focus rating + meeting-density chart.

## Milestones
- W1: schema, OAuth, dummy prompt loop
- W2: real ritual flow, Slack integration, opt-in telemetry shim
- W3: pilot with 3 internal participants, fix instrumentation gaps
- W4: deploy

## Risks for the coding agent to flag
- handle calendar conflicts (back-to-back) — collapse prompts so we don't spam
- timezone bugs around DST
- telemetry helper auto-update story

## Definition of done
- 18-participant deployment runs for 4 weeks without manual intervention
- raw data exports cleanly to a single Parquet file per participant
- no PII leaves the participant's machine without explicit consent`,
  },

  protocol: {
    title: 'validation protocol',
    subtitle: 'human-subjects script + measures',
    kind: 'human-study',
    color: '#d9a548',
    filename: 'PROTOCOL.md',
    body: (ctx) => `# Validation protocol
> Generated by Probe · stage 4 · for the human-subjects portion of ${ctx.designName}

## Goal
Run the study described in the plan. Produce data that lets us answer:
${ctx.rqs.map((r) => `  • RQ ${r.letter} — ${r.rq}`).join('\n')}

## Recruitment
${ctx.recruitment}

Channels: Prolific (general remote workers), targeted Slack groups (eng/PM/design),
internal call for an org-cohort if available.

Screener (web form, ~2 min)
1. How many video calls do you typically have on a working day? (drop-down 0–10+)
2. Are you working remotely ≥ 3 days/week? (Y/N — gate)
3. Role family: engineering / PM / design / other
4. Time zone (drop-down)
5. Two short consent questions on telemetry willingness.

## Consent
- Plain-language consent form, IRB-light template.
- Separate opt-in for typing-cadence telemetry; never bundled with main consent.
- Right to withdraw at any time, no questions asked, full data deletion within 14 days.

## Sessions / fielding
Phase 1 — onboarding (30 min, video call)
  • walk through tools, calendar OAuth, desktop helper install
  • collect baseline questionnaire (Zoom Exhaustion & Fatigue Scale, demographics)
  • set expectations: prompts post-meeting, weekly digest, exit interview

Phase 2 — fielding (4 weeks)
  • automatic prompts post-meeting; participant fills in <90s
  • weekly check-in via Slack DM (1 question, "anything weird this week?")
  • light-touch nudge if engagement <60%

Phase 3 — exit interview (60 min, semi-structured)
  • walk through participant's own data with them (member-checking)
  • probe for texture-of-experience (RQ C anchor)
  • body-mapping exercise: 10 min toward end

## Measures
- ZEFS (validated), administered baseline + week 4
- post-meeting focus self-report, 1–7 Likert
- adherence rate (n_completed / n_prompted)
- typing cadence (only telemetry opt-ins)
- thematic codes from exit-interview transcripts

## Analysis plan (pre-registered)
- mixed-effects model: focus_rating ~ meeting_density + agenda_present + (1 | participant)
- ITT for the within-subjects ritual phase
- iterative coding (two coders, κ ≥ 0.7) for interview transcripts
- triangulation memo: where do quant + qual converge / diverge?

## Ethics
- IRB-light approval before any participant contact
- no manager will ever see individual participant data
- compensation: $80 baseline + $20/week of full participation
- debrief after exit interview includes a 1-page personal data report

## Dropouts / contingencies
- if adherence < 50% in week 1 → check-in call, simplify prompt
- if recruitment short by >30% by day 7 → widen screener or extend window`,
  },

  survey: {
    title: 'survey instrument',
    subtitle: 'cross-org questionnaire · ~12 min',
    kind: 'survey',
    color: '#7dcfff',
    filename: 'SURVEY.md',
    body: (ctx) => `# Survey instrument
> Generated by Probe · stage 4 · cross-org questionnaire

Target N = 400 (powered for medium effects, allows role × tenure breakdown)

## Sections

### A · Eligibility & demographics (5 items)
A1. How many days/week do you work remotely? [drop-down 0–7]
A2. How many video calls did you have yesterday? [open numeric]
A3. Role family [eng / PM / design / research / other]
A4. Tenure in current role (years) [open]
A5. Org size [<50, 50–250, 250–1000, 1000+]

### B · Meeting load & shape (6 items)
Likert 1–7, "describes my typical week."
B1. My meetings are mostly back-to-back.
B2. Most meetings I attend have an agenda.
B3. I often have 6+ attendees in a typical meeting.
B4. I feel I can decline meetings without consequence.
B5. My calendar is mostly booked by others.
B6. I have ≥ 60 minutes of uninterrupted focus time most days.

### C · Fatigue (use ZEFS · validated 15 items)

### D · Recovery rituals (8 items)
D1. Do you do anything specific between meetings? [open free-text → coded]
D2–D7. Likert: "I take a short walk / breathe / journal / step outside / drink water / look away from screen."
D8. If you had a 90-second guided ritual app, would you use it? [Y/N + why]

### E · Open-ended (2 items)
E1. Describe a recent video-call day where focus held up well. What helped?
E2. Describe one where it didn't. What broke?

## Logic
- C → D order is fixed (don't bias recovery answers with fatigue cuing).
- Anyone scoring < 4 days/week remote at A1 is screened out at intake.

## Distribution
Prolific (n=300 stratified by role) + internal Slack (n≈100, voluntary).
Estimated cost: $1,800 + $0 internal.`,
  },

  diary: {
    title: 'diary / ESM kit',
    subtitle: 'post-meeting prompt + weekly digest',
    kind: 'esm',
    color: '#c8a8e6',
    filename: 'DIARY_KIT.md',
    body: (ctx) => `# Diary / ESM kit
> Generated by Probe · stage 4 · 2-week post-meeting prompt set

## Trigger
Fire 5 minutes after every calendar event tagged "meeting" with ≥ 2 attendees.

## Prompt (≤ 90 seconds)
1. Right now, how focused do you feel? [1–7 slider, anchored "scattered" / "sharp"]
2. How was that meeting? [tag list: agenda? · decisions made? · I contributed? · drained me? · energized me?]
3. Anything you want to remember about it? [optional 1-line text]

## Skip behaviour
Two skips in a row → switch to once-daily digest at end-of-day for that participant.

## Weekly digest (pushed Sunday evening)
Show participant their own:
  • avg focus by day-of-week
  • meeting count vs. focus scatter
  • top 3 meeting tags they associated with low focus
Use this in member-checking during the exit interview (Phase 3 of the protocol).

## Completion target
≥ 70% of triggered prompts answered to count as a valid week.

## Privacy
All free-text stays on the participant's account; researchers see aggregates by default.
Exit-interview member-checking is the only point we read individual prompt responses with the participant.`,
  },

  irb: {
    title: 'IRB-light memo',
    subtitle: 'one-pager for ethics review',
    kind: 'ethics',
    color: '#e26e6e',
    filename: 'IRB_MEMO.md',
    body: (ctx) => `# IRB-light memo
> Generated by Probe · stage 4 · one-page ethics summary

Title: ${ctx.designName}
PI: [your name]
Duration: ${ctx.duration}

## Purpose
Investigate the questions:
${ctx.rqs.map((r) => `  • RQ ${r.letter} — ${r.rq}`).join('\n')}

## Population
Adult remote knowledge workers, ≥ 3 days/week remote, ≥ 3 video calls/day.
Stratified across role (eng/PM/design) and tenure to address known sampling gaps.

## Risk profile
Minimal. No deception. No physiological measurement. No sensitive populations.
Primary risks: time burden (~3h total over 4 weeks), discomfort recalling stressful workdays.

## Data
- Self-report focus ratings, free text, interview transcripts.
- Optional typing-cadence telemetry (separate consent, never required).
- Stored in a private project-scoped Postgres; no third-party analytics.

## Consent
Two-tier: main study consent at intake, separate telemetry consent before any
desktop instrumentation. Right to withdraw without explanation; full data deletion
within 14 days of request.

## Compensation
$80 baseline + $20/week of completed participation. Pro-rated on withdrawal.

## Reporting
- Aggregate-only in any external write-up.
- Individual data reviewed only with the participant during member-checking.
- 5-year retention; encrypted at rest; PI is sole custodian.

Approved by: ____________________   Date: ____________________`,
  },
};

function Artifacts({ chosenDesign, plan, selectedBranches, onBack, onContinue, goTo }) {
  const wants = decideArtifacts(plan, chosenDesign);
  const [stage, setStage] = useState(0); // 0 = drafting, 1 = revealed
  const [openId, setOpenId] = useState(null); // expanded artifact
  const [edits, setEdits] = useState({});      // id → edited body
  const [editing, setEditing] = useState(null);
  const [liveBodies, setLiveBodies] = useState({}); // id → body string from /api/probe/artifacts

  useEffect(() => {
    const t = setTimeout(() => setStage(1), 1100);
    // Replace stock artifact bodies with LLM-generated ones if we
    // have a design + plan. We don't change the artifact list (still
    // driven by decideArtifacts) — only the body content.
    if (chosenDesign && plan) {
      fetch('/api/probe/artifacts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          design: {
            id: chosenDesign.id || 'custom',
            name: chosenDesign.name || '',
            weeks: parseInt(chosenDesign.duration || '12', 10) || 12,
            arc: chosenDesign.arc || '',
            summary: chosenDesign.summary || '',
            coverage: {},
            strengths: chosenDesign.strengths || [],
            tensions: chosenDesign.tensions || [],
          },
          plan: {
            phases: (plan.phases || []).map((p) => ({ weeks: p.weeks || 1, name: p.name || '', detail: p.detail || '' })),
            deliverables: plan.deliverables || [],
            recruitment: plan.recruitment || '',
            totalWeeks: parseInt(plan.timeline || '12', 10) || 12,
            risks: plan.risks || [],
          },
        }),
      })
        .then((r) => r.ok ? r.json() : null)
        .then((data) => {
          if (!data || !Array.isArray(data.artifacts)) return;
          // The LLM emits kinds ('spec', 'protocol', 'irb', 'survey',
          // 'diary') as id, but decideArtifacts above wants 'impl' for
          // the implementation plan. Normalise so live bodies actually
          // replace the stock ones rather than being silently dropped.
          const aliasFromLLM = (id) => (id === 'spec' ? 'impl' : id);
          const map = {};
          for (const a of data.artifacts) {
            const localId = aliasFromLLM(a.id);
            if (localId && a.body) map[localId] = a.body;
          }
          setLiveBodies(map);
        })
        .catch(() => { /* keep stock bodies */ });
    }
    return () => clearTimeout(t);
  }, []);

  // Hotkeys
  useEffect(() => {
    const onKey = (e) => {
      const tag = (e.target && e.target.tagName) || '';
      if (tag === 'INPUT' || tag === 'TEXTAREA') return;
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      if (e.key === 'Escape') { e.preventDefault(); if (editing) setEditing(null); else if (openId) setOpenId(null); else onBack(); }
      const digit = parseInt(e.key, 10);
      if (!Number.isNaN(digit) && digit >= 1 && digit <= wants.length) {
        e.preventDefault();
        const id = wants[digit - 1];
        setOpenId((o) => o === id ? null : id);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [wants.length, openId, editing]);

  const ctx = {
    designName: chosenDesign?.name || 'the chosen study design',
    duration: chosenDesign?.duration || '—',
    rqs: selectedBranches,
    recruitment: plan?.recruitment || '—',
  };

  const bodyOf = (id) => {
    if (edits[id] !== undefined) return edits[id];
    if (liveBodies[id]) return liveBodies[id];
    return ARTIFACT_DEFS[id].body(ctx);
  };

  const copy = (id) => {
    const text = bodyOf(id);
    navigator.clipboard?.writeText(text);
  };
  const download = (id) => {
    const def = ARTIFACT_DEFS[id];
    const blob = new Blob([bodyOf(id)], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = def.filename;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Crumb steps={[
        ['probe', palette.amber, 'probe'],
        ['new project', palette.ink2, 'new project'],
        ['brainstorm', palette.ink2, 'brainstorm'],
        ['literature', palette.ink2, 'literature'],
        ['methodology', palette.ink2, 'methodology'],
        ['artifacts', palette.ink, 'artifacts'],
      ]} onStepClick={goTo}
      right={
        <span style={{ display: 'flex', gap: 14, alignItems: 'center' }}>
          <span style={{ color: palette.ink3 }}>stage 4 · artifacts</span>
          <button onClick={onBack} style={ghostBtnStyle}><kbd style={kbdStyle}>esc</kbd> back</button>
        </span>
      } />

      <div style={{ flex: 1, padding: '28px 32px 80px', maxWidth: 1100, margin: '0 auto', width: '100%' }}>
        <div style={{ color: palette.ink3, fontSize: 11, letterSpacing: '0.14em',
          textTransform: 'uppercase', marginBottom: 8 }}>
          ─── artifact agents · drafting handoff documents ───
        </div>
        <h2 style={{ fontSize: 18, fontWeight: 500, margin: 0, color: palette.ink2 }}>
          Probe wrote the documents your design needs. Edit anything, then copy or download.
        </h2>

        {stage === 0 ? (
          <>
            {window.ModelStatusLine && (
              <div className="fade-in" style={{ padding: '14px 0 6px' }}>
                <window.ModelStatusLine
                  model="claude-sonnet-4-6"
                  phase={window.PhaseDots ? (
                    <window.PhaseDots
                      phases={['planning', 'drafting', 'formatting', 'verifying']}
                      activeIdx={1}
                      accent={palette.amber}
                      compact
                    />
                  ) : null}
                  accent={palette.amber}
                  running
                />
              </div>
            )}
            <DraftingRow wants={wants} />
          </>
        ) : (
          <div style={{ marginTop: 22, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {wants.map((id, i) => {
              const def = ARTIFACT_DEFS[id];
              const open = openId === id;
              const isEditing = editing === id;
              return (
                <div key={id} className="fade-in" style={{
                  border: `1px solid ${palette.rule}`,
                  borderLeft: `3px solid ${def.color}`,
                  background: palette.bg2, borderRadius: 4,
                }}>
                  {/* Header row — entire row toggles open/close. role/tabIndex
                      promote it to a real button for keyboard users; the kbd
                      number badge gets its own explicit click so users who
                      click "1/2/3" expecting a button don't fall through. */}
                  <div
                    role="button"
                    tabIndex={isEditing ? -1 : 0}
                    onClick={() => !isEditing && setOpenId((o) => o === id ? null : id)}
                    onKeyDown={(e) => {
                      if (isEditing) return;
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault();
                        setOpenId((o) => o === id ? null : id);
                      }
                    }}
                    style={{
                      cursor: isEditing ? 'default' : 'pointer',
                      padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 10,
                      outline: 'none',
                    }}>
                    <span
                      onClick={(e) => {
                        if (isEditing) return;
                        e.stopPropagation();
                        setOpenId((o) => o === id ? null : id);
                      }}
                      style={{ ...kbdStyle, fontSize: 10, color: palette.ink3, cursor: isEditing ? 'default' : 'pointer' }}>{i + 1}</span>
                    <span style={{ color: def.color, fontSize: 16, lineHeight: 1, marginRight: 4 }}>▸</span>
                    <span style={{ color: palette.ink, fontWeight: 600, fontSize: 14 }}>{def.title}</span>
                    <span style={{ ...chipStyle, color: def.color, borderColor: def.color }}>{def.kind}</span>
                    <span style={{ color: palette.ink3, fontSize: 12 }}>· {def.subtitle}</span>
                    <span style={{ color: palette.ink3, fontSize: 11, marginLeft: 'auto' }}>{def.filename}</span>
                    <span style={{ color: palette.ink3, fontSize: 11, transform: open ? 'rotate(90deg)' : 'none', display: 'inline-block', transition: 'transform 120ms' }}>›</span>
                  </div>

                  {open && (
                    <div className="fade-in" style={{
                      padding: '14px 16px', borderTop: `1px solid ${palette.rule}`,
                      background: palette.bg, borderRadius: '0 0 3px 3px',
                    }}>
                      {/* toolbar */}
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 10 }}>
                        <span style={{ color: palette.ink3, fontSize: 11 }}>{def.filename} · markdown</span>
                        <span style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
                          {!isEditing ? (
                            <>
                              <button onClick={() => setEditing(id)} style={artifactIconBtn}>edit</button>
                              <button onClick={() => copy(id)} style={artifactIconBtn}>copy</button>
                              <button onClick={() => download(id)} style={artifactIconBtn}>download</button>
                            </>
                          ) : (
                            <>
                              <button onClick={() => setEditing(null)} style={artifactIconBtn}>done</button>
                              <button onClick={() => { setEdits((e) => { const n = { ...e }; delete n[id]; return n; }); }} style={artifactIconBtn}>reset</button>
                            </>
                          )}
                        </span>
                      </div>
                      {isEditing ? (
                        <textarea value={bodyOf(id)} onChange={(e) => setEdits((m) => ({ ...m, [id]: e.target.value }))}
                          style={{
                            width: '100%', minHeight: 360, boxSizing: 'border-box',
                            background: palette.bg, color: palette.ink, fontFamily: 'inherit', fontSize: 12.5,
                            border: `1px solid ${palette.rule}`, padding: '10px 12px', borderRadius: 3,
                            outline: 'none', resize: 'vertical', lineHeight: 1.55,
                            caretColor: palette.amber,
                          }} />
                      ) : (
                        <div style={{
                          maxHeight: 480, overflow: 'auto',
                          padding: '4px 4px',
                        }}>
                          {window.MarkdownText
                            ? <window.MarkdownText text={bodyOf(id)} />
                            : <pre style={{
                                margin: 0, color: palette.ink, fontFamily: 'inherit', fontSize: 12.5,
                                lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word',
                              }}>{bodyOf(id)}</pre>}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* footer */}
      <div style={{
        position: 'sticky', bottom: 0, background: palette.bg,
        borderTop: `1px solid ${palette.rule}`,
        padding: '10px 22px', display: 'flex', alignItems: 'center', gap: 14,
        color: palette.ink3, fontSize: 12.5,
      }}>
        <span><kbd style={kbdStyle}>1</kbd>..<kbd style={kbdStyle}>{wants.length}</kbd> open artifact</span>
        <span><kbd style={kbdStyle}>esc</kbd> back</span>
        <span style={{ marginLeft: 'auto', display: 'flex', gap: 12, alignItems: 'center' }}>
          <span>{wants.length} artifacts ready</span>
          <button disabled={stage < 1} onClick={() => stage >= 1 && onContinue && onContinue()} style={{
            background: stage < 1 ? 'transparent' : palette.amber,
            color: stage < 1 ? palette.ink4 : palette.bg,
            border: `1px solid ${stage < 1 ? palette.rule : palette.amber}`,
            padding: '5px 14px', borderRadius: 3, fontFamily: 'inherit', fontSize: 12, fontWeight: 600,
            cursor: stage < 1 ? 'not-allowed' : 'pointer',
            display: 'inline-flex', alignItems: 'center', gap: 8,
          }}>
            continue · simulate evaluation
            <kbd style={{ ...kbdStyle, background: stage < 1 ? palette.bg2 : 'rgba(0,0,0,0.2)',
              color: stage < 1 ? palette.ink4 : 'rgba(0,0,0,0.7)',
              borderColor: stage < 1 ? palette.rule : 'rgba(0,0,0,0.15)' }}>↵</kbd>
          </button>
        </span>
      </div>
    </div>
  );
}

function DraftingRow({ wants }) {
  return (
    <div style={{
      marginTop: 22, padding: '14px 16px',
      background: palette.bg2, border: `1px solid ${palette.rule}`, borderRadius: 4,
    }}>
      <div style={{ color: palette.ink3, fontSize: 11, letterSpacing: '0.12em',
        textTransform: 'uppercase', marginBottom: 10 }}>agents working</div>
      {wants.map((id, i) => {
        const def = ARTIFACT_DEFS[id];
        return (
          <div key={id} style={{
            display: 'flex', alignItems: 'center', gap: 10,
            padding: '6px 0', color: palette.ink2, fontSize: 13,
          }}>
            <span className="pulse-dot" style={{ color: def.color, fontSize: 14 }}>●</span>
            <span>drafting <span style={{ color: def.color }}>{def.title}</span></span>
            <span style={{ color: palette.ink3, fontSize: 11 }}>· {def.filename}</span>
          </div>
        );
      })}
    </div>
  );
}

const artifactIconBtn = {
  background: 'transparent', border: `1px solid ${palette.rule}`, color: palette.ink2,
  fontFamily: 'inherit', fontSize: 11, padding: '3px 9px', borderRadius: 3, cursor: 'pointer',
};

function Crumb({ steps, right, onStepClick }) {
  return (
    <div style={{
      padding: '14px 22px', display: 'flex', alignItems: 'center', gap: 12,
      borderBottom: `1px solid ${palette.rule}`, color: palette.ink3, fontSize: 12,
    }}>
      {steps.map((step, i) => {
        const [s, c, key] = step;
        const isLast = i === steps.length - 1;
        const clickable = !isLast && onStepClick;
        return (
          <React.Fragment key={i}>
            <span
              onClick={clickable ? () => onStepClick(key || s) : undefined}
              onMouseEnter={clickable ? (e) => { e.currentTarget.style.textDecoration = 'underline'; } : undefined}
              onMouseLeave={clickable ? (e) => { e.currentTarget.style.textDecoration = 'none'; } : undefined}
              style={{ color: c, cursor: clickable ? 'pointer' : 'default' }}
            >{s}</span>
            {i < steps.length - 1 && <span>›</span>}
          </React.Fragment>
        );
      })}
      <span style={{ marginLeft: 'auto' }}>{right}</span>
    </div>
  );
}

window.Artifacts = Artifacts;
