/**
 * Reviewer-disagreement HTML panel generator — `probe panel <run_id> <branch>`.
 *
 * Produces a static three-column HTML page that renders the reviewer
 * findings side-by-side with the meta-reviewer verdict as a banner.
 * Reviewer 1 of the internal audit specifically called this out as the
 * demo-video Frame 6 replacement: more load-bearing than a screenshot
 * walkthrough, and it showcases Opus 4.7's core capability bet
 * (sustained role-separation with preserved disagreement).
 *
 * The page is self-contained: no external CSS or JS, one-file, renders
 * in any browser. The source artifacts are the reviewer JSONs already
 * on disk; zero API cost.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk';
import { branchDir } from '../util/paths.js';
import { palette, brand } from '../ui/theme.js';

interface ReviewerFinding {
  reviewer_persona: string;
  decisive_weakness: string;
  recommendation: string;
  criticisms?: Array<{
    severity?: string;
    violated_criterion?: string;
    why_matters?: string;
    required_change?: string;
    evidence_span?: { quote?: string; source?: string };
  }>;
}

interface MetaReview {
  verdict: string;
  disagreement_classification: string;
  verdict_rationale: string;
  reviewers_read?: string[];
  disagreement_matrix?: Array<{
    reviewer: string;
    recommendation: string;
    decisive_weakness: string;
  }>;
}

export interface PanelOptions {
  runId: string;
  branchId: string;
  outputPath?: string;
}

export async function renderReviewerPanel(opts: PanelOptions): Promise<string> {
  const bd = branchDir(opts.runId, opts.branchId);
  const reviewsDir = path.join(bd, 'reviews');

  const files = await fs.readdir(reviewsDir);
  const reviews: ReviewerFinding[] = [];
  for (const f of files.sort()) {
    if (!f.endsWith('.json')) continue;
    const raw = await fs.readFile(path.join(reviewsDir, f), 'utf8');
    reviews.push(JSON.parse(raw) as ReviewerFinding);
  }

  if (reviews.length === 0) {
    throw new Error(`no reviewer findings at ${reviewsDir}`);
  }

  let meta: MetaReview | null = null;
  try {
    const metaPath = path.join(bd, 'meta_review.json');
    meta = JSON.parse(await fs.readFile(metaPath, 'utf8')) as MetaReview;
  } catch {
    /* optional */
  }

  const html = buildPanelHtml(opts.runId, opts.branchId, reviews, meta);

  const outputPath = opts.outputPath ?? path.join(bd, 'REVIEWER_PANEL.html');
  await fs.writeFile(outputPath, html);
  console.log(
    brand.header('🎭 reviewer panel rendered') +
      chalk.hex(palette.dim)(' → ') +
      outputPath,
  );
  return outputPath;
}

function buildPanelHtml(
  runId: string,
  branchId: string,
  reviews: ReviewerFinding[],
  meta: MetaReview | null,
): string {
  const reviewerColumns = reviews.map(renderReviewerColumn).join('\n');
  const metaBanner = meta ? renderMetaBanner(meta) : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Probe reviewer panel · ${escapeHtml(runId)} · branch ${escapeHtml(branchId)}</title>
<style>
${PANEL_CSS}
</style>
</head>
<body>
<header class="panel-header">
  <h1>🔬 Probe reviewer panel</h1>
  <div class="meta-line">
    <span class="run-id">${escapeHtml(runId)}</span>
    <span class="dot">·</span>
    <span class="branch-id">branch ${escapeHtml(branchId)}</span>
    <span class="dot">·</span>
    <span class="count">${reviews.length} reviewers</span>
  </div>
  <p class="subtitle">Each column is an independent Opus 4.7 session under a different reviewer persona. The meta-reviewer reads all findings; its verdict is at the bottom.</p>
</header>

<main class="grid">
${reviewerColumns}
</main>

${metaBanner}

<footer class="footer">
  <p>All three reviewer findings are <code>[AGENT_INFERENCE]</code> — they reflect Probe's reviewer agents' judgment, not evidence from real participants. The researcher is expected to read these alongside the guidebook and decide which revisions to prioritize.</p>
  <p class="attribution">Generated by <code>probe panel ${escapeHtml(runId)} ${escapeHtml(branchId)}</code> · <a href="https://github.com/Apolotary/probe-researcher">github.com/Apolotary/probe-researcher</a></p>
</footer>
</body>
</html>`;
}

function renderReviewerColumn(r: ReviewerFinding): string {
  const color = personaColor(r.reviewer_persona);
  const criticisms = (r.criticisms ?? [])
    .slice(0, 5)
    .map((c) => {
      const severityClass = c.severity ? `severity-${c.severity}` : '';
      const evidence = c.evidence_span?.quote
        ? `<blockquote><span class="source">(${escapeHtml(c.evidence_span.source ?? 'artifact')})</span> ${escapeHtml(truncate(c.evidence_span.quote, 220))}</blockquote>`
        : '';
      return `<li class="${severityClass}">
        <div class="crit-head"><span class="severity-badge ${severityClass}">${escapeHtml(c.severity ?? '')}</span> ${escapeHtml(c.violated_criterion ?? '')}</div>
        ${evidence}
        <p class="crit-body">${escapeHtml(truncate(c.why_matters ?? '', 320))}</p>
        <p class="required-change"><strong>Required:</strong> ${escapeHtml(truncate(c.required_change ?? '', 260))}</p>
      </li>`;
    })
    .join('\n');

  return `<section class="reviewer" style="border-top-color: ${color}">
  <header>
    <h2 style="color: ${color}">${escapeHtml(formatPersona(r.reviewer_persona))}</h2>
    <div class="recommendation"><span class="rec-badge rec-${escapeHtml(r.recommendation)}">${escapeHtml(r.recommendation)}</span></div>
  </header>
  <div class="decisive">
    <div class="decisive-label">DECISIVE WEAKNESS</div>
    <p class="decisive-body">${escapeHtml(r.decisive_weakness)}</p>
  </div>
  <div class="criticisms">
    <div class="criticisms-label">${(r.criticisms ?? []).length} criticisms${(r.criticisms ?? []).length > 5 ? ' (showing 5)' : ''}</div>
    <ul>${criticisms}</ul>
  </div>
</section>`;
}

function renderMetaBanner(meta: MetaReview): string {
  const verdictClass = `verdict-${meta.verdict}`;
  const matrix = (meta.disagreement_matrix ?? [])
    .map(
      (r) =>
        `<div class="mx-row"><span class="mx-name">${escapeHtml(formatPersona(r.reviewer))}</span><span class="mx-rec rec-${escapeHtml(r.recommendation)}">${escapeHtml(r.recommendation)}</span></div>`,
    )
    .join('\n');
  return `<section class="meta-banner ${verdictClass}">
  <header>
    <h3>Meta-reviewer verdict</h3>
    <div class="verdict-badge ${verdictClass}">${escapeHtml(meta.verdict)}</div>
    <div class="classification">${escapeHtml(meta.disagreement_classification)}</div>
  </header>
  <div class="meta-matrix">${matrix}</div>
  <p class="meta-rationale">${escapeHtml(meta.verdict_rationale)}</p>
</section>`;
}

function personaColor(persona: string): string {
  if (persona === 'methodologist') return '#1B365D';
  if (persona === 'accessibility_advocate') return '#7a2d5a';
  if (persona === 'novelty_hawk') return '#8a6500';
  return '#333';
}

function formatPersona(persona: string): string {
  return persona
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + '…';
}

const PANEL_CSS = `
* { box-sizing: border-box; }
body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #f7f5ef;
  color: #1a1a1a;
  margin: 0;
  padding: 24px;
  line-height: 1.5;
}
.panel-header {
  max-width: 1400px;
  margin: 0 auto 24px;
  padding: 18px 22px;
  background: #fff;
  border: 0.8pt solid #d0cbb8;
  border-radius: 4px;
}
.panel-header h1 { margin: 0; font-size: 22pt; color: #1a1d2c; letter-spacing: -0.01em; }
.meta-line { margin: 6px 0; color: #555; font-size: 10.5pt; }
.meta-line .run-id { font-family: 'JetBrains Mono', monospace; background: #ede9dc; padding: 1px 7px; border-radius: 2px; }
.meta-line .branch-id { color: #1B365D; font-weight: 600; }
.meta-line .dot { margin: 0 9px; color: #aaa; }
.subtitle { margin: 10px 0 0; color: #555; font-size: 10.5pt; }

.grid {
  max-width: 1400px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: 18px;
}

.reviewer {
  background: #fff;
  border: 0.8pt solid #d0cbb8;
  border-top: 4px solid #333;
  border-radius: 4px;
  padding: 16px 18px;
}
.reviewer header { border-bottom: 0.6pt solid #e8e3d4; padding-bottom: 10px; margin-bottom: 12px; }
.reviewer h2 { margin: 0 0 4px; font-size: 13pt; letter-spacing: -0.005em; }
.rec-badge {
  display: inline-block;
  font-family: 'JetBrains Mono', monospace;
  font-size: 9.5pt;
  font-weight: 500;
  padding: 3px 10px;
  border-radius: 3px;
  background: #ede9dc;
  color: #333;
}
.rec-reject { background: #ffdad5; color: #8a1e12; }
.rec-major_revision { background: #fff1d2; color: #8a5c00; }
.rec-minor_revision { background: #ede9dc; color: #555; }
.rec-accept_revise { background: #e1f5e0; color: #1f6b1e; }
.rec-human_judgment_required { background: #e8ecf7; color: #1B365D; }

.decisive {
  background: #fffbf4;
  border-left: 3px solid #1B365D;
  padding: 10px 14px;
  margin: 0 0 14px;
  border-radius: 0 3px 3px 0;
}
.decisive-label { font-size: 8.5pt; font-weight: 600; letter-spacing: 0.08em; color: #1B365D; margin-bottom: 4px; }
.decisive-body { margin: 0; font-size: 10.5pt; line-height: 1.55; color: #1a1a1a; font-weight: 500; }

.criticisms-label { font-size: 9pt; color: #777; margin-bottom: 8px; font-weight: 500; }
.criticisms ul { margin: 0; padding: 0; list-style: none; }
.criticisms li {
  border-top: 0.4pt solid #eee;
  padding: 10px 0;
  font-size: 10pt;
}
.criticisms li:first-child { border-top: none; padding-top: 0; }
.crit-head { font-weight: 600; color: #1a1a1a; margin-bottom: 4px; }
.severity-badge {
  display: inline-block;
  font-family: 'JetBrains Mono', monospace;
  font-size: 8pt;
  padding: 1px 6px;
  border-radius: 2px;
  margin-right: 6px;
  vertical-align: 1pt;
  background: #ede9dc;
  color: #666;
}
.severity-blocking { background: #ffdad5; color: #8a1e12; }
.severity-major { background: #fff1d2; color: #8a5c00; }
.severity-minor { background: #e1f5e0; color: #1f6b1e; }

.criticisms blockquote {
  background: #f9f6ec;
  border-left: 2pt solid #c5c0b0;
  margin: 6px 0;
  padding: 6px 10px;
  font-size: 9pt;
  font-style: italic;
  color: #555;
  line-height: 1.45;
}
.criticisms blockquote .source { font-style: normal; color: #888; font-family: 'JetBrains Mono', monospace; font-size: 8pt; margin-right: 4px; }
.crit-body { margin: 4px 0; color: #333; font-size: 9.5pt; line-height: 1.5; }
.required-change { margin: 4px 0 0; font-size: 9pt; color: #444; line-height: 1.5; }
.required-change strong { color: #1a1a1a; }

.meta-banner {
  max-width: 1400px;
  margin: 22px auto 0;
  padding: 18px 22px;
  background: #fff;
  border-radius: 4px;
  border: 0.8pt solid #d0cbb8;
  border-left: 5px solid #1B365D;
}
.meta-banner.verdict-reject { border-left-color: #8a1e12; }
.meta-banner.verdict-human_judgment_required { border-left-color: #1B365D; }
.meta-banner.verdict-accept_revise { border-left-color: #1f6b1e; }
.meta-banner h3 { margin: 0 0 4px; font-size: 11.5pt; color: #1a1d2c; letter-spacing: -0.005em; }
.verdict-badge {
  display: inline-block;
  font-family: 'JetBrains Mono', monospace;
  font-size: 10pt;
  font-weight: 600;
  padding: 4px 12px;
  border-radius: 3px;
  background: #e8ecf7;
  color: #1B365D;
  margin-right: 10px;
}
.verdict-reject { background: #ffdad5; color: #8a1e12; }
.verdict-human_judgment_required { background: #e8ecf7; color: #1B365D; }
.verdict-accept_revise { background: #e1f5e0; color: #1f6b1e; }
.classification { display: inline-block; font-size: 9.5pt; color: #666; font-family: 'JetBrains Mono', monospace; }
.meta-matrix { margin: 14px 0 12px; display: flex; flex-wrap: wrap; gap: 12px; }
.mx-row { display: flex; align-items: center; gap: 8px; background: #faf8f0; padding: 6px 12px; border-radius: 3px; font-size: 9.5pt; }
.mx-name { font-weight: 500; color: #444; }
.mx-rec { font-family: 'JetBrains Mono', monospace; font-size: 9pt; padding: 1px 7px; border-radius: 2px; }
.meta-rationale { margin: 0; font-size: 10.5pt; line-height: 1.55; color: #333; }

.footer {
  max-width: 1400px;
  margin: 30px auto 0;
  padding: 14px 22px 18px;
  border-top: 0.5pt solid #d0cbb8;
  color: #666;
  font-size: 9pt;
}
.footer p { margin: 4px 0; }
.footer code { background: #ede9dc; padding: 1px 4px; border-radius: 2px; font-family: 'JetBrains Mono', monospace; font-size: 9pt; color: #444; }
.footer a { color: #1B365D; text-decoration: none; border-bottom: 0.5pt dotted #1B365D; }
.attribution { color: #888; font-size: 8.5pt; }
`.trim();
